name: irc
version: 4.0.0
authors:
- Kenneth Endfinger <kaendfinger@gmail.com>
- samrg472 <samrg472@gmail.com>
- TheMike <zeusintraining@gmail.com>
- Logan Gorence <loganjohngorence@gmail.com>
description: Simple IRC library in Dart
homepage: https://github.com/SpinlockLabs/irc.dart/
environment:
  sdk: ">=2.0.0 <3.0.0"
dependencies:
  glob: "^1.1.7"
  pedantic: "^1.5.0"
dev_dependencies:
  test: "^1.3.2"
