name: irc
version: 3.1.0
authors:
- Kenneth Endfinger <kaendfinger@gmail.com>
- samrg472 <samrg472@gmail.com>
- TheMike <zeusintraining@gmail.com>
- Logan Gorence <loganjohngorence@gmail.com>
description: A beautiful all-purpose IRC library.
homepage: https://github.com/SpinlockLabs/irc.dart/
environment:
  sdk: '>=1.9.0'
dependencies:
  event_dispatcher: "^1.2.2"
  quiver: "^0.26.2"
dev_dependencies:
  test: "^0.12.28"
