name: irc
description: A feature-full Dart IRC library
version: 1.1.9
authors:
- Kenneth Endfinger <kaendfinger@gmail.com>
- samrg472 <samrg472@gmail.com>
homepage: https://github.com/kaendfinger/irc.dart/
documentation: http://www.dartdocs.org/documentation/irc/1.1.9/
environment:
  sdk: ">=1.2.0"
dependencies:
  event_bus: ">=0.2.4 <0.3.0"
dev_dependencies:
  hop: "0.31.0"
  yaml: "0.10.0"
  quiver: "0.19.0-dev.1"
