name: irc
description: A feature-full Dart IRC library
version: 1.1.5
author: Kenneth Endfinger <kaendfinger@gmail.com>
homepage: https://github.com/kaendfinger/irc.dart/
dependencies:
  event_bus: ">=0.2.4 <0.3.0"
  irc_message: ">=1.0.0 <2.0.0"
  quiver: ">=0.18.2 <0.19.0"
dev_dependencies:
  hop: 0.31.0