name: irc
version: 1.4.5
authors:
- Kenneth Endfinger <kaendfinger@gmail.com>
- samrg472 <samrg472@gmail.com>
- TheMike <zeusintraining@gmail.com>
description: A beautiful all-purpose IRC library
homepage: https://github.com/DirectMyFile/irc.dart/
environment:
  sdk: '>=1.5.0'
dependencies:
  event_dispatcher: '>=1.0.0 <2.0.0'
  quiver: '>=0.18.2 <0.20.0'
dev_dependencies:
  hop: '>=0.31.0+1 <0.32.0'
  yaml: '>=2.0.0 <3.0.0'
  unittest: '>=0.11.0+3 <0.12.0'
