name: irc
version: 4.0.3
authors:
- Kenneth Endfinger <kaendfinger@gmail.com>
- Logan Gorence <logan@gorence.xyz>
description: IRC library in Dart providing a simplistic and easy to use API.
homepage: https://github.com/SpinlockLabs/irc.dart/
environment:
  sdk: ">=2.2.0 <3.0.0"
dependencies:
  glob: "^2.0.1"
  pedantic: "^1.11.0"
dev_dependencies:
  test: "^1.16.8"
