name: irc
version: 1.2.7
authors:
- Kenneth Endfinger <kaendfinger@gmail.com>
- samrg472 <samrg472@gmail.com>
- TheMike <zeusintraining@gmail.com>
description: A feature-full Dart IRC library
# TODO: Create Polymer-based site
homepage: https://github.com/DirectMyFile/irc.dart/
environment:
  # TODO: Review new features in latest SDKs and eventually update this
  sdk: '>=1.2.0'
dependencies:
  event_dispatcher: '>=0.0.5 <0.1.0'
dev_dependencies:
  hop: 0.31.0
  yaml: 0.10.0
