name: irc
version: 4.0.3
authors:
- Kenneth Endfinger <kaendfinger@gmail.com>
- Logan Gorence <logan@gorence.xyz>
description: IRC library in Dart providing a simplistic and easy to use API.
homepage: https://github.com/SpinlockLabs/irc.dart/
environment:
  sdk: ">=2.0.0 <3.0.0"
dependencies:
  glob: "^1.2.0"
  pedantic: "^1.9.2"
dev_dependencies:
  test: "^1.15.7"
