analyzer.files: 
  - lib/irc.dart
  - example/log.dart
  - example/debug.dart
  - example/example.dart
  - example/parsing.dart
check.tasks: 
  - analyze
  - test
docs.output: out/docs
test.file: test/all_tests.dart